name: qamqor_clinic
description: "Qamqor Clinic - Private clinic mobile application."
publish_to: 'none'  # Уберите эту строку, если хотите опубликовать на pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  dio: ^5.8.0+1       # Версия Dio
  dio_cookie_manager: ^2.0.1 # Пакет для работы с cookie в Dio
  cookie_jar: ^3.0.0  
  video_player: ^2.9.2
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.0.0
  url_launcher: ^6.0.9
  flutter_animate: ^4.5.2
  path_provider: ^2.1.1
  provider: ^6.0.5
  image_picker: ^0.8.5+3
  carousel_slider: ^5.0.0
  workmanager: ^0.5.2
  google_fonts: ^6.0.0
  rflutter_alert: ^2.0.7
  lottie: ^3.1.3
  model_viewer_plus: ^1.9.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Укажите папку с изображениями
  assets:
    - assets/logo.png
    - assets/animation/
    - .env
    

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
